import React from 'react';

/**
 * Transforms routes generated by vite-plugin-pages (Next.js file-system style)
 * into a structure compatible with React Router's createBrowserRouter.
 *
 * @param {Array} rawRoutes - The raw array from `import routes from '~pages'`
 * @returns {Array} Formatted route objects ready for createBrowserRouter()
 */
export function formatNextRoutes(rawRoutes = []) {
  return processRouteList(rawRoutes);
}

/**
 * Processes an array of sibling routes at any tree level.
 * Extracts layouts and nests remaining routes under them.
 */
function processRouteList(routes = []) {
  if (!Array.isArray(routes) || routes.length === 0) return [];

  // 1. Separate the layout route from page/folder routes
  const layoutRoute = routes.find(
    (r) => r.path === 'layout' || r.path?.endsWith('/layout')
  );
  const siblingRoutes = routes.filter((r) => r !== layoutRoute);

  // 2. Process all non-layout sibling routes recursively
  const processedSiblings = siblingRoutes
    .map((route) => processSingleNode(route))
    .filter(Boolean);

  // 3. If a layout exists in this folder/level, wrap all siblings inside it
  if (layoutRoute) {
    const layoutComp = layoutRoute.element || layoutRoute.component;

    return [
      {
        element: renderElement(layoutComp),
        children: processedSiblings,
      },
    ];
  }

  return processedSiblings;
}

/**
 * Processes an individual route node.
 */
function processSingleNode(route) {
  if (!route) return null;

  const processed = { ...route };

  // Convert path syntax (Extended to check not-found patterns)
  if (route.path?.endsWith('/page') || route.path === 'page') {
    processed.index = true;
    delete processed.path;
  } else if (route.path) {
    processed.path = cleanPath(route.path);
  }

  // Convert component/element to a rendered React Element
  const comp = route.element || route.component;
  if (comp) {
    processed.element = renderElement(comp);
    delete processed.component;
  }

  // Recursively process child folders/routes
  if (route.children && route.children.length > 0) {
    processed.children = processRouteList(route.children);
  }

  return processed;
}

/**
 * Helper to ensure components are converted into valid React Elements (<Component />)
 */
function renderElement(ComponentOrElement) {
  if (!ComponentOrElement) return undefined;
  if (React.isValidElement(ComponentOrElement)) return ComponentOrElement;
  return React.createElement(ComponentOrElement);
}

/**
 * Converts Next.js path conventions to React Router syntax.
 */
function cleanPath(rawPath) {
  let path = rawPath;

  // Extended catch-all & Not Found patterns:
  // Catches: 404, not-found, [...notFound], [...404], [...slug], etc.
  const isNotFound = 
    path === '404' ||
    path === 'not-found' ||
    path.endsWith('/404') ||
    path.endsWith('/not-found') ||
    /\[\.\.\.?(notFound|404)\]/i.test(path);

  if (isNotFound) {
    return '*';
  }

  // Extended: Convert double-bracket optional catch-all / optional params:
  // [[...slug]] -> *
  // [[id]] -> :id?
  path = path.replace(/\[\[\.\.\.([^\]]+)\]\]/g, '*');
  path = path.replace(/\[\[([^\]]+)\]\]/g, ':$1?');

  // Convert catch-all: [...slug] -> *
  path = path.replace(/\[\.\.\.([^\]]+)\]/g, '*');

  // Convert standard dynamic params: [id] -> :id
  path = path.replace(/\[([^\]]+)\]/g, ':$1');

  return path;
}